### ISSUE TITLE
Promise is not defined

### ISSUE THREAD

**Issue by Cottin** [twitter-fabric/velocity-react#13]
Is it just me? :)

Following your steps:

```
$ git clone https://github.com/twitter-fabric/velocity-react.git
$ cd velocity-react
$ npm install
$ npm run demo
```

Gives me the following errors:
```
ERROR in ./~/css-loader!./demo/css/flexbox.css
Module build failed: ReferenceError: Promise is not defined
    at LazyResult.async (/Users/superman/velocity-react/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:152:31)
    at LazyResult.then (/Users/superman/velocity-react/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:75:21)
    at processCss (/Users/superman/velocity-react/node_modules/css-loader/lib/processCss.js:174:5)
    at Object.module.exports (/Users/superman/velocity-react/node_modules/css-loader/lib/loader.js:22:2)
 @ ./demo/css/flexbox.css 4:14-81 13:2-17:4 14:20-87

ERROR in ./~/css-loader!./demo/css/loading-placeholder.css
Module build failed: ReferenceError: Promise is not defined
    at LazyResult.async (/Users/superman/velocity-react/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:152:31)
    at LazyResult.then (/Users/superman/velocity-react/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:75:21)
    at processCss (/Users/superman/velocity-react/node_modules/css-loader/lib/processCss.js:174:5)
    at Object.module.exports (/Users/superman/velocity-react/node_modules/css-loader/lib/loader.js:22:2)
 @ ./demo/css/loading-placeholder.css 4:14-93 13:2-17:4 14:20-99

ERROR in ./~/css-loader!./demo/css/polyfill.css
Module build failed: ReferenceError: Promise is not defined
    at LazyResult.async (/Users/superman/velocity-react/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:152:31)
    at LazyResult.then (/Users/superman/velocity-react/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:75:21)
    at processCss (/Users/superman/velocity-react/node_modules/css-loader/lib/processCss.js:174:5)
    at Object.module.exports (/Users/superman/velocity-react/node_modules/css-loader/lib/loader.js:22:2)
 @ ./demo/css/polyfill.css 4:14-82 13:2-17:4 14:20-88
```

**Comment by phopkins** [comment]
Are you running Node 0.10 or earlier? Sounds like some of the CSS libraries require at least Node 0.12: https://github.com/webpack/css-loader/issues/144

**Comment by Cottin** [comment]
Ahh, that's probably it, thanks!

```
node -v
v0.10.26
```
